### ISSUE TITLE
Sequence acquisition fails when camera exposure long enough to return a single image per second

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift-instrumentation-kit#203]
With the shown parameters in the image. (Acquired item is number 10 on the image)

This issue is to figure out *why* it has failed, and whether it's an issue or not.

![Image](https://github.com/user-attachments/assets/9a297dea-35f0-473d-9375-72e45913d88b)

**Comment by Ion-e** [comment]
This bug is a bit of a mess.

The original issue was triggered with the following parameters:
![Image](https://github.com/user-attachments/assets/2d6980dd-aab4-4383-8c16-00e66a397ea7)

However there seems to be a different issue whilst doing an acquisition with the following parameters:
![Image](https://github.com/user-attachments/assets/d3417f9f-0e85-4494-9c4a-b21dcbcf94df)

I have managed to reproduce the latest one, do you want me to close this ticket and create 2 new tickets for them? @cmeyer

**Comment by jamesrussell216** [comment]
@Ion-e can you check with @Brow71189 or @bentps whether we're trying to do something non-sensicle here!

**Comment by cmeyer** [comment]
Fresh launch of Swift, run scan briefly, stop it, then use these parameters and it seems to work for me with latest version. So I can't reproduce this issue without further info.

<img width="389" alt="Image" src="https://github.com/user-attachments/assets/1e30eeb3-6faa-40e4-9bf0-f649d8e85d6e" />

**Comment by Ion-e** [comment]
Confirmed this happens consistently.


![Image](https://github.com/user-attachments/assets/105ce9da-a475-4a36-a0e0-cc08413343c5)

**Comment by jamesrussell216** [comment]
Happens for me too. @cmeyer try it with "Spectra" selected instead of "Image"...

![Image](https://github.com/user-attachments/assets/ddf7bdbd-c59c-4872-8897-3fbaf9b6c89a)

Stack trace:
Acquisition (Acquire) started: 2025-01-29 15:00:29.296122
Traceback (most recent call last):
File "c:\nionapps\swift\nionswift-instrumentation-kit\nion\instrumentation\Acquisition.py", line 3028, in acquire
    data_stream_.send_raw_data_stream_event_to_data_handler(raw_data_stream_event)
File "c:\nionapps\swift\nionswift-instrumentation-kit\nion\instrumentation\Acquisition.py", line 689, in send_raw_data_stream_event_to_data_handler
    self.__unprocessed_data_handler.handle_data_available(data_stream_event)
File "c:\nionapps\swift\nionswift-instrumentation-kit\nion\instrumentation\Acquisition.py", line 2521, in handle_data_available
    self.send_packet(packet)
File "c:\nionapps\swift\nionswift-instrumentation-kit\nion\instrumentation\Acquisition.py", line 2513, in send_packet
    self.__data_handler.handle_data_available(packet)
File "c:\nionapps\swift\nionswift-instrumentation-kit\nion\instrumentation\Acquisition.py", line 2794, in handle_data_available
    self.__framer.data_available(packet, typing.cast(FrameCallbacks, self))
File "c:\nionapps\swift\nionswift-instrumentation-kit\nion\instrumentation\Acquisition.py", line 1828, in data_available
    source_data = data_stream_event.source_data.reshape(data_stream_event.source_data.shape[1:])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 32768 into shape (512,)
Acquisition (Acquire) finished: 2025-01-29 15:00:32.162712 canceled with error

**Comment by Ion-e** [comment]
Aclaration. There seems to be a few different errors here and last few comments only

**Comment by cmeyer** [comment]
If there are other issues, can you file them individually in new issues and close this one?

**Comment by Ion-e** [comment]
Both issues confirmed as fixed.

Thanks!
