### ISSUE TITLE
Test test_si_with_drift_correction_within_scan intermittently fail assert (but succeeds test)

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift-instrumentation-kit#206]
Stack trace

```
/Users/user/Developer/Nion/MasterProject/nionswift-instrumentation-kit/nion/instrumentation/scan_base.py:1137: DeprecationWarning: There is no current event loop
  self.__settings.initialize(configuration_location=configuration_location, event_loop=asyncio.get_event_loop())
Traceback (most recent call last):
  File "/Users/user/Developer/Nion/MasterProject/nionswift-instrumentation-kit/nion/instrumentation/Acquisition.py", line 3016, in acquire
    data_stream_.send_raw_data_stream_event_to_data_handler(raw_data_stream_event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/Nion/MasterProject/nionswift-instrumentation-kit/nion/instrumentation/Acquisition.py", line 689, in send_raw_data_stream_event_to_data_handler
    self.__unprocessed_data_handler.handle_data_available(data_stream_event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/Nion/MasterProject/nionswift-instrumentation-kit/nion/instrumentation/Acquisition.py", line 2549, in handle_data_available
    self.__data_handlers[i].handle_data_available(packet)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/user/Developer/Nion/MasterProject/nionswift-instrumentation-kit/nion/instrumentation/Acquisition.py", line 2591, in handle_data_available
    self.__process_packet(packet)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/user/Developer/Nion/MasterProject/nionswift-instrumentation-kit/nion/instrumentation/Acquisition.py", line 2670, in __process_packet
    assert current_index + remaining_count <= collection_count
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by cmeyer** [comment]
357e031e5dff62c99097882fc93143204f6fa4e7
